all:
	javac -encoding utf-8 Hello.java -classpath "../.."
	javac -encoding utf-8 Frequencer.java -classpath "../.."
	javac -encoding utf-8 InformationEstimator.java -classpath "../.."
	javac -encoding utf-8 TestCase.java -classpath "../.."
run:
#	java -classpath "../.." s4.b173307/Hello
# 	java -Decoding=utf-8 -classpath "../.." s4.b173307/Frequencer
#	java -classpath "../.." s4.b173307/InformationEstimator
	java -classpath "../.." s4.b173307/TestCase
